"use client";
import type {MouseEvent} from "react";
import Button from "@/components/_ui/button"; import {Checkbox} from "@/components/_ui/checkbox"; import Tag from "@/components/_ui/tag"; import {TableCell,TableRow} from "@/components/_ui/table"; import SegmentBar from "@/components/_common/segment-bar"; import Sparkline from "@/components/_common/sparkline"; import {TAG_TONES,type Company} from "@/data/classmates"; import {formatDate,formatMoney,splitTags} from "@/lib/classmates"; import {cn} from "@/lib/utils"; import {TABLE_CELL_CLASS,TABLE_ROW_CLASS,columnClass,type TableColumnKey} from "./table-columns"; import CalendarIcon from "@/public/assets/images/_common/calendar.svg"; import DotsIcon from "@/public/assets/images/classmates/table/dots-horizontal.svg";
type Props={classmate:Company;selected:boolean;active:boolean;onToggle:()=>void;onOpen:()=>void;onOpenOwner:()=>void};
function stop(e:MouseEvent){e.stopPropagation()}
export default function ClassmateRow({classmate,selected,active,onToggle,onOpen,onOpenOwner}:Props){const {visible,hidden}=splitTags(classmate.tags);return <TableRow role="row" onClick={onOpen} data-active={active||selected} className={cn(TABLE_ROW_CLASS,"hover:bg-card/60 data-[active=true]:border-card data-[active=true]:bg-card cursor-pointer")}>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("name"))}><span className="flex items-center gap-5"><Checkbox checked={selected} onCheckedChange={onToggle} onClick={stop} aria-label={`Select ${classmate.name}`}/>{classmate.name}</span></TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("segment"))}><span className="flex items-center gap-[3px]">{visible.map(tag=><Tag key={tag} tone={TAG_TONES[tag]}>{tag}</Tag>)}{hidden>0&&<Tag tone="neutral" size="sm">+{hidden}</Tag>}</span></TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("owner"))}><span className="truncate">Eze Kelvin</span></TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("openDeals"))}>{classmate.openDeals}</TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("pipelineValue"))}><span className="flex items-center gap-1"><span className="text-muted-foreground">₦</span>{formatMoney(classmate.pipelineValue)}</span></TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("winProbability"))}><span className="flex items-center gap-2"><SegmentBar percent={classmate.winProbability} className="w-[74px]"/><span className="w-[4ch] text-right">{classmate.winProbability===100?"Paid":"Unpaid"}</span></span></TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("trend"))}><Sparkline values={classmate.trend}/></TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("lastInteraction"))}><span className="flex items-center gap-1"><CalendarIcon aria-hidden className="text-foreground size-3.5 shrink-0"/><span className="tabular-nums">{formatDate(classmate.lastInteraction.date)}</span><span aria-hidden className="mx-[3px] h-2 w-px bg-white/15"/>{classmate.lastInteraction.label}</span></TableCell>
<TableCell role="cell" className={cn(TABLE_CELL_CLASS,columnClass("action"))} onClick={stop}><Button variant="ghost" size="icon-sm" className={cn("text-foreground",active&&"bg-white/6")} aria-label={`Open ${classmate.name} details`} onClick={onOpen}><DotsIcon aria-hidden className="size-3"/></Button></TableCell></TableRow>}
